/**
 * Comprehensive List of Cities in Pakistan (Categorized by Province / Territory)
 * Modeled after OLX.com.pk location hierarchy.
 */

export const POPULAR_CITIES = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad",
  "Bahawalpur",
  "Sargodha",
  "Abbottabad",
  "Sukkur",
];

export const PROVINCE_CITIES = {
  "Federal Capital": [
    "Islamabad",
  ],
  "Punjab": [
    "Lahore",
    "Rawalpindi",
    "Faisalabad",
    "Multan",
    "Gujranwala",
    "Sialkot",
    "Bahawalpur",
    "Sargodha",
    "Sheikhupura",
    "Rahim Yar Khan",
    "Jhang",
    "Dera Ghazi Khan",
    "Gujrat",
    "Sahiwal",
    "Wah Cantt",
    "Kasur",
    "Okara",
    "Chiniot",
    "Kamoke",
    "Hafizabad",
    "Sadiqabad",
    "Burewala",
    "Khanewal",
    "Muzaffargarh",
    "Mandi Bahauddin",
    "Jhelum",
    "Khanpur",
    "Pakpattan",
    "Daska",
    "Gojra",
    "Muridke",
    "Bahawalnagar",
    "Samundri",
    "Jaranwala",
    "Chishtian",
    "Attock",
    "Vehari",
    "Kot Abdul Malik",
    "Ferozwala",
    "Chakwal",
    "Kamalia",
    "Ahmedpur East",
    "Kot Addu",
    "Wazirabad",
    "Layyah",
    "Taxila",
    "Khushab",
    "Mianwali",
    "Lodhran",
    "Hasilpur",
    "Bhakkar",
    "Arif Wala",
    "Sambrial",
    "Jatoi",
    "Haroonabad",
    "Narowal",
    "Bhalwal",
    "Pattoki",
    "Shakargarh",
    "Mian Channu",
    "Jalalpur Jattan",
    "Kabirwala",
    "Alipur",
    "Chunian",
    "Sangla Hill",
    "Pasrur",
    "Kot Radha Kishan",
    "Taunsa Sharif",
    "Murree",
  ],
  "Sindh": [
    "Karachi",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Nawabshah",
    "Kotri",
    "Mirpur Khas",
    "Shikarpur",
    "Jacobabad",
    "Khairpur",
    "Dadu",
    "Tando Allahyar",
    "Tando Adam",
    "Umerkot",
    "Shahdadkot",
    "Badin",
    "Ghotki",
    "Daharki",
    "Kandhkot",
    "Thatta",
    "Kashmore",
    "Sehwan",
    "Moro",
    "Kandiaro",
    "Matiari",
    "Tando Muhammad Khan",
    "Jamshoro",
    "Sanghar",
    "Shahdadpur",
    "Naushahro Feroze",
    "Mehar",
    "Gambat",
    "Ratodero",
    "Rohri",
    "Hala",
  ],
  "Khyber Pakhtunkhwa": [
    "Peshawar",
    "Mardan",
    "Mingora (Swat)",
    "Abbottabad",
    "Kohat",
    "Dera Ismail Khan",
    "Mansehra",
    "Swabi",
    "Nowshera",
    "Charsadda",
    "Haripur",
    "Bannu",
    "Swat",
    "Batkhela",
    "Timergara",
    "Karak",
    "Tank",
    "Hangu",
    "Risalpur",
    "Topi",
    "Chitral",
    "Parachinar",
    "Dir",
    "Malakand",
  ],
  "Balochistan": [
    "Quetta",
    "Turbat",
    "Khuzdar",
    "Hub",
    "Chaman",
    "Gwadar",
    "Sibi",
    "Zhob",
    "Loralai",
    "Dera Allah Yar",
    "Dera Murad Jamali",
    "Kalat",
    "Mastung",
    "Nushki",
    "Pishin",
    "Usta Mohammad",
    "Panjgur",
    "Kharan",
    "Pasni",
    "Ormara",
  ],
  "Azad Jammu & Kashmir": [
    "Muzaffarabad",
    "Mirpur",
    "Kotli",
    "Rawalakot",
    "Bagh",
    "Bhimber",
    "Pallandri",
    "Hattian Bala",
    "Haveli",
  ],
  "Gilgit-Baltistan": [
    "Gilgit",
    "Skardu",
    "Hunza",
    "Chilas",
    "Ghanche",
    "Astore",
    "Nagar",
  ],
};

// Unique alphabetical list of all Pakistani cities
const allCitiesSet = new Set();
Object.values(PROVINCE_CITIES).forEach((list) => {
  list.forEach((city) => allCitiesSet.add(city));
});

export const ALL_PAKISTANI_CITIES = Array.from(allCitiesSet).sort((a, b) =>
  a.localeCompare(b)
);

export const CITIES_WITH_ALL = ["All Cities", ...ALL_PAKISTANI_CITIES];
